apiVersion: apps/v1
kind: Deployment
metadata: expense-tracker-backend
spec:
    replicas: 2
    selector:
      matchLabels:
        app: java-app
    template:
      #pod
      spec:
        containers:
          #java-app
          - name: expense-tracker-backend
            image: parthkarad/expense-tracker:latest
            ports:
              - containerPort: 8081
          #db
          - name: mongo-db
            image: mongo
            ports:
              - containerPort: 27017

