version: '3.8'
services:
  expense-tracker:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MONGODB_URL=mongodb://mongo:27017/expense-tracker
    volumes:
      - ./:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
 mongodb:
 mongodb_config: