version: '3.8'
services:
    expense-tracker:
      image: parthkarad/expense-tracker:${TAG}
      hostname: expense-java-app
      ports:
        - "8081:8080"
      environment:
        - SERVER_PORT=8080
        - MONGODB_URL=mongodb://mongo:27017/expense-tracker
      volumes:
        - ./:/app
      networks:
        - expense
      depends_on:
        - mongo

    mongo:
      image: mongo
      hostname: mydb
      ports:
        - 27017:27017
      volumes:
        - mongodb:/data/db
        - mongodb_config:/data/configdb
      networks:
        - expense
volumes:
 mongodb:
 mongodb_config:

networks:
  expense:
    name: expense
    external: true
