apiVersion: v1
kind: Service
metadata:
  name:  expense-tracker-backend-service
spec:
  selector:
    app: java-app
  type: NodePort #Service Type
  ports:
  - protocol: TCP
    port: 8081 #Service port
    targetPort: 8081 #container java port
    nodePort: 30004 #expose outside node
